### ISSUE TITLE
Missing build script commit to repo?

### ISSUE THREAD

**Issue by programmin1** [ezra-project/ezra-project-docker#1]
The build script seems to be missing some files. I was going to see if I could build it - 

```
ezra-bible-app-docker/docker$ sh ./build_ubuntu_2204.sh 
npm ERR! missing script: build-linux

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2022-06-08T02_14_34_371Z-debug.log
npm ERR! missing script: deb_2204

npm ERR! A complete log of this run can be found in:
npm ERR!    ~/.npm/_logs/2022-06-08T02_14_34_721Z-debug.log
cp: cannot stat 'release/packages/*.deb': No such file or directory
```

**Comment by tobias-klein** [comment]
This is not meant to be used like that.

The purpose of this Docker based build approach is to use it in combination with GitHub Actions. Technically you could also use it locally, but for that you need to:
1) Run the Docker container interactively
2) Clone the ezra-bible-app repo within the Docker container
3) Then run the build script

I am closing this issue, since no scripts are missing here - they are part of the ezra-bible-app repo.

**Comment by programmin1** [comment]
Alright, I don't quite understand that but I was just trying this out to see if I could get it to build arm64 .deb for Librem 5 for example.
